### ISSUE TITLE
Post API의 파라미터의 명칭에 관한 건

### ISSUE THREAD

**Issue by elliotyim** [devv-up/frontend#7]
현재 포스팅과 관련한 api는 model.py에서 사용하는 필드명을 camelCase로 바꿔서 사용하려고 생각중입니다.
ex) GET api-test.dev-up.kr/posts?category=1&tags=2&startDate=2020-01-01&endDate=2020-02-02

아직 확정된 사안이 아니기에 이와 관련해서 의견이 있으시면 코멘트 부탁드립니다.

**Comment by devgaram** [comment]
나중에 api문서만 공유해주시면 될 것 같아요.
