### ISSUE TITLE
태그의 파라미터 형식에 관한 건

### ISSUE THREAD

**Issue by elliotyim** [devv-up/frontend#8]
현재 포스팅 되어있는 태그를 필터링 할 때, tags를 파라미터로 넘겨주는 방식은 아래의 두 가지 방법이 고려됩니다.
1. GET /posts?tags=1,2,3,...
2. GET /posts?tags=1&tags=2&tags=3...

두 방법 다 가능하며, 기왕이면 한 방법만 쓰고 나머지 방법을 막아버리려고 하는데,
어떤 방법으로 파라미터를 받는게 좋을지 의견 부탁드립니다.

**Comment by devgaram** [comment]
확인해보니깐 1번 방식으로 해놨더라구요. 1번이 좋을 듯 싶습니다.

**Comment by elliotyim** [comment]
넵 알겠습니다.
